App\IdentityBundle\Message\Registration:
    constraints:
        - App\CommonBundle\Validator\Constraints\UniqueModel:
            entityClass: App\IdentityBundle\Entity\Account
            fields: [ email ]
    properties:
        firstName:
            - Length:
                min: 1
                max: 50
        lastName:
            - Length:
                min: 1
                max: 100
        email:
            - Email: ~
            - Length:
                min: 1
                max: 255
        password:
            - Length:
                min: 6
                max: 255
