App\CompanyBundle\Message\CreateCompany:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 1
                max: 255
        address:
            - Length:
                min: 1
                max: 255
        logoFile:
            - Image:
                minWidth: 200
                maxWidth: 400
                minHeight: 200
                maxHeight: 400
