app_identity_registration_index:
    path:       /sign-up
    defaults:   { _controller: App\IdentityBundle\Controller\RegistrationController::index }
    methods:    [GET, POST]

app_identity_auth_login:
    path:       /sign-in
    defaults:   { _controller: App\IdentityBundle\Controller\AuthController::login }
    methods:    [GET, POST]

app_identity_auth_logout:
    path:       /sign-out
    defaults:   { _controller: App\IdentityBundle\Controller\AuthController::logout }
    methods:    [GET, POST]
