App\CompanyBundle\Entity\Department:
    type: entity
    table: company_department
    repositoryClass: App\CompanyBundle\Repository\DoctrineDepartmentRepository
    id:
        id:
            type: string
    fields:
        name:
            type: string
        employeeCount:
            type: integer
            options:
                default: 0
        description:
            type: string
            nullable: true
    manyToOne:
        head:
            targetEntity: App\CompanyBundle\Entity\Employee
            mappedBy: headOfDepartmentList
            cascade: [ persist, remove ]
            joinColumn:
                name: head_id
                referencedColumnName: id
                nullable: false
        company:
            targetEntity: App\CompanyBundle\Entity\Company
            mappedBy: departmentList
            cascade: [ persist, remove ]
            joinColumn:
                name: company_id
                referencedColumnName: id
                nullable: false
