App\CompanyBundle\Entity\Position:
    type: entity
    table: company_position
    repositoryClass: App\CompanyBundle\Repository\DoctrinePositionRepository
    id:
        id:
            type: string
    fields:
        name:
            type: string
        employeeCount:
            type: integer
            options:
                default: 0
    manyToOne:
        company:
            targetEntity: App\CompanyBundle\Entity\Company
            mappedBy: positionList
            cascade: [ persist, remove ]
            joinColumn:
                name: company_id
                referencedColumnName: id
                nullable: false
