App\Hrm\Identity\Model\Account:
    type: entity
    table: hrm_identity_account
    repositoryClass: App\Hrm\IdentityBundle\Repository\DoctrineAccountRepository
    uniqueConstraints:
        uk__account__email:
            columns: [ email ]
    id:
        id:
            type: string
    fields:
        email:
            type: string
            length: 180
            unique: true
        passwordHash:
            type: string
            length: 256
        roles:
            type: simple_array
        createdAt:
            type: datetime_immutable
    oneToOne:
        profile:
            targetEntity: App\Hrm\Identity\Model\Profile
            mappedBy: account
            cascade: [ persist, remove ]
    manyToMany:
        ownedCompanyList:
            targetEntity: App\Hrm\Company\Model\Company
            mappedBy: ownerList
