App\Hrm\Identity\Model\Profile:
    type: entity
    table: hrm_identity_profile
    repositoryClass: App\Hrm\IdentityBundle\Repository\DoctrineProfileRepository
    uniqueConstraints:
        uk__profile__account_id:
            columns: [ account_id ]
    indexes:
        idx__profile__first_name:
            columns: [ first_name ]
        idx__profile__last_name:
            columns: [ last_name ]
        idx__profile__birth_date:
            columns: [ birth_date ]
    id:
        id:
            type: string
    fields:
        firstName:
            type: string
            length: 50
        lastName:
            type: string
            length: 100
        middleName:
            type: string
            length: 100
            nullable: true
        photoPath:
            type: string
            length: 256
            nullable: true
        address:
            type: string
            length: 256
            nullable: true
        birthDate:
            type: datetime
            nullable: true
    oneToOne:
        account:
            targetEntity: App\Hrm\Identity\Model\Account
            cascade: [ persist, remove ]
            joinColumn:
                name: account_id
                referencedColumnName: id
                nullable: false
    oneToMany:
        contactList:
            targetEntity: App\Hrm\Identity\Model\Contact
            mappedBy: profile
            cascade: [ persist, remove ]
