App\Hrm\Identity\Domain\Model\Profile\Profile:
    type: entity
    table: profile
    repositoryClass: App\Hrm\IdentityBundle\Repository\Profile\DoctrineProfileRepository
    indexes:
        idx_profile_first_name:
            columns: [ first_name ]
        idx_profile_last_name:
            columns: [ last_name ]
        idx_profile_birth_date:
            columns: [ birth_date ]
    uniqueConstraints:
        uk_profile_profile_id_account_id:
            columns: [ id, account_id ]
    id:
        id:
            type: !php/const App\Hrm\IdentityBundle\Doctrine\DBAL\Types\Profile\ProfileIdType::NAME
    fields:
        accountId:
            type: !php/const App\Hrm\IdentityBundle\Doctrine\DBAL\Types\Account\AccountIdType::NAME
        firstName:
            type: string
            length: 50
        lastName:
            type: string
            length: 100
        middleName:
            type: string
            length: 100
            nullable: true
        photoPath:
            type: string
            length: 256
            nullable: true
        address:
            type: string
            length: 256
            nullable: true
        birthDate:
            type: datetime
            nullable: true
