App\Hrm\Identity\Domain\Model\User\User:
    type: entity
    table: user
    repositoryClass: App\Hrm\IdentityBundle\Repository\DoctrineUserRepository
    uniqueConstraints:
        uk_user_email:
            columns: [ email ]
    id:
        id:
            type: !php/const App\Hrm\IdentityBundle\Doctrine\DBAL\Types\User\UserIdType::NAME
    fields:
        email:
            type: !php/const App\Hrm\CommonBundle\Doctrine\DBAL\Types\EmailType::NAME
            length: 180
            unique: true
        passwordHash:
            type: string
            length: 256
        roles:
            type: !php/const App\Hrm\IdentityBundle\Doctrine\DBAL\Types\User\UserRoleType::NAME
        isEmailConfirmed:
            type: boolean
            options:
                default: false
        canLoggedIn:
            type: boolean
            options:
                default: true
        createdAt:
            type: datetime_immutable
        loggedInAt:
            type: datetime
            nullable: true
