doctrine:
    dbal:
        types:
            !php/const App\Hrm\CommonBundle\Doctrine\DBAL\Types\EmailType::NAME: App\Hrm\CommonBundle\Doctrine\DBAL\Types\EmailType
            !php/const App\Hrm\IdentityBundle\Doctrine\DBAL\Types\Account\AccountIdType::NAME: App\Hrm\IdentityBundle\Doctrine\DBAL\Types\Account\AccountIdType
            !php/const App\Hrm\IdentityBundle\Doctrine\DBAL\Types\Account\AccountRoleType::NAME: App\Hrm\IdentityBundle\Doctrine\DBAL\Types\Account\AccountRoleType
            !php/const App\Hrm\IdentityBundle\Doctrine\DBAL\Types\Profile\ContactIdType::NAME: App\Hrm\IdentityBundle\Doctrine\DBAL\Types\Profile\ContactIdType
            !php/const App\Hrm\IdentityBundle\Doctrine\DBAL\Types\Profile\ProfileIdType::NAME: App\Hrm\IdentityBundle\Doctrine\DBAL\Types\Profile\ProfileIdType

        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        default_entity_manager: default
        mappings:
            AppHrmIdentityDomainModel:
                type: yml
                prefix: App\Hrm\Identity\Domain\Model
                dir: '%kernel.project_dir%/src/Hrm/IdentityBundle/Resources/config/doctrine'
                is_bundle: false
