doctrine:
    dbal:
        types:
            !php/const App\Hrm\CommonBundle\Doctrine\DBAL\Types\EmailType::NAME: App\Hrm\CommonBundle\Doctrine\DBAL\Types\EmailType
            !php/const App\Hrm\IdentityBundle\Doctrine\DBAL\Types\User\UserIdType::NAME: App\Hrm\IdentityBundle\Doctrine\DBAL\Types\User\UserIdType
            !php/const App\Hrm\IdentityBundle\Doctrine\DBAL\Types\User\UserRoleType::NAME: App\Hrm\IdentityBundle\Doctrine\DBAL\Types\User\UserRoleType

        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        default_entity_manager: default
        mappings:
            AppHrmIdentityDomainModel:
                type: yml
                prefix: App\Hrm\Identity\Domain\Model
                dir: '%kernel.project_dir%/src/Hrm/IdentityBundle/Resources/config/doctrine'
                is_bundle: false
