twig:
    globals:
        # icons https://themes-pixeden.com/font-demos/7-stroke/
        menu:
            -
                name: Главная
                icon: home
                items:
                    -
                        name: Dashboard
                        link: app_hrm_dashboard_home_index
                        icon: monitor
                        items: ~
            -
                name: Компания
                icon: culture
                items:
                    -
                        name: Настройки
                        link: ~
                        icon: ~
                        items:
                            -
                                name: Создать компанию
                                link: app_hrm_company_settings_create_index
                                icon: ~
                                items: ~
#                            -
#                                name: Присоединиться к компании
#                                link: #
#                                icon: ~
#                                items: ~
