App\IdentityBundle\Message\Registration:
    constraints:
        - App\CommonBundle\Validator\Constraints\UniqueModel:
            entityClass: App\IdentityBundle\Entity\Account
            fields: [ email ]
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 1
                max: 100
        email:
            - NotBlank: ~
            - Email: ~
            - Length:
                min: 1
                max: 255
        password:
            - NotBlank: ~
            - Length:
                min: 6
                max: 255
