services:

    _defaults:
        autowire: true
        autoconfigure: true


    # Controller

    App\Hrm\CompanyBundle\Controller\:
        autowire: true
        resource: '../../Controller'
        tags: ['controller.service_arguments']
    

    # Repository

    App\Hrm\Company\Repository\CompanyRepository: '@App\Hrm\CompanyBundle\Repository\DoctrineCompanyRepository'
    App\Hrm\CompanyBundle\Repository\DoctrineCompanyRepository:
        factory: ['@doctrine', getRepository]
        arguments:
            - App\Hrm\Company\Model\Company
