services:

    _defaults:
        autowire: true
        autoconfigure: true

    # Controller
    App\Hrm\CompanyBundle\Controller\:
        autowire: true
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    # Fixture
    App\Hrm\CompanyBundle\DataFixtures\:
        autowire: true
        resource: '../../DataFixtures'
        tags: ['doctrine.fixture.orm']

    # Message Handler
    App\Hrm\Company\MessageHandler\:
        resource: '%kernel.project_dir%/src/Hrm/Company/MessageHandler'
        tags: ['messenger.message_handler']


    # Service

    App\Hrm\Company\Service\LogoFileSystem:
        arguments:
            $logoPathFileDirectory: 'company_logo'
            $filesystem: '@default.storage'


    # Repository

    App\Hrm\Company\Repository\CompanyRepository: '@App\Hrm\CompanyBundle\Repository\DoctrineCompanyRepository'
    App\Hrm\CompanyBundle\Repository\DoctrineCompanyRepository:
        factory: ['@doctrine', getRepository]
        arguments:
            - App\Hrm\Company\Model\Company
    
    App\Hrm\Company\Repository\OfficeRepository: '@App\Hrm\CompanyBundle\Repository\DoctrineOfficeRepository'
    App\Hrm\CompanyBundle\Repository\DoctrineOfficeRepository:
        factory: ['@doctrine', getRepository]
        arguments:
            - App\Hrm\Company\Model\Office

    App\Hrm\Company\Repository\DepartmentRepository: '@App\Hrm\CompanyBundle\Repository\DoctrineDepartmentRepository'
    App\Hrm\CompanyBundle\Repository\DoctrineDepartmentRepository:
        factory: ['@doctrine', getRepository]
        arguments:
            - App\Hrm\Company\Model\Department

    App\Hrm\Company\Repository\PositionRepository: '@App\Hrm\CompanyBundle\Repository\DoctrinePositionRepository'
    App\Hrm\CompanyBundle\Repository\DoctrinePositionRepository:
        factory: ['@doctrine', getRepository]
        arguments:
            - App\Hrm\Company\Model\Position

    App\Hrm\Company\Repository\EmployeeRepository: '@App\Hrm\CompanyBundle\Repository\DoctrineEmployeeRepository'
    App\Hrm\CompanyBundle\Repository\DoctrineEmployeeRepository:
        factory: ['@doctrine', getRepository]
        arguments:
            - App\Hrm\Company\Model\Employee

    App\Hrm\Company\Repository\EmployeeRequestRepository: '@App\Hrm\CompanyBundle\Repository\DoctrineEmployeeRequestRepository'
    App\Hrm\CompanyBundle\Repository\DoctrineEmployeeRequestRepository:
        factory: ['@doctrine', getRepository]
        arguments:
            - App\Hrm\Company\Model\EmployeeRequest
