services:
    _defaults:
        autowire: true
        autoconfigure: true


    # Service

    App\Hrm\CommonBundle\Service\GenerateUuid: ~
    App\Hrm\Common\Service\GenerateIdentifier: '@App\Hrm\CommonBundle\Service\GenerateUuid'
    
    App\Hrm\CommonBundle\Service\DoctrineCommitTransaction: ~
    App\Hrm\Common\Service\CommitTransaction: '@App\Hrm\CommonBundle\Service\DoctrineCommitTransaction'
