services:
    _defaults:
        autowire: true
        autoconfigure: true


    # Service

    App\Hrm\CommonBundle\Service\GenerateUuidService: ~
    App\Hrm\Common\Service\GenerateIdentifierService: '@App\Hrm\CommonBundle\Service\GenerateUuidService'
    
    App\Hrm\CommonBundle\Service\DoctrineCommitTransactionService: ~
    App\Hrm\Common\Service\CommitTransactionService: '@App\Hrm\CommonBundle\Service\DoctrineCommitTransactionService'
