app_identity:
    resource: '@IdentityBundle/Resources/config/routing.yml'
    prefix: /

app_company:
    resource: '@CompanyBundle/Resources/config/routing.yml'
    prefix: /dash/company

app_dashboard_company:
    resource: '@DashboardBundle/Resources/config/routing.yml'
