app_hrm_identity:
    resource: '@HrmIdentityBundle/Resources/config/routing.yml'
    prefix: /

app_hrm_company:
    resource: '@HrmCompanyBundle/Resources/config/routing.yml'
    prefix: /dash/company

app_dashboard_company:
    resource: '@HrmDashboardBundle/Resources/config/routing.yml'
