app_hrm_identity:
    resource: '@HrmIdentityBundle/Resources/config/routing.yml'
    prefix: /auth

app_hrm_company:
    resource: '@HrmCompanyBundle/Resources/config/routing.yml'
    prefix: /company
